name: purr
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/cat.gif
    - assets/cat_icon.png
    - assets/sleep.png
    - assets/unsure.png

    - assets/food/avacado.png
    - assets/food/cake.png
    - assets/food/cherry.png
    - assets/food/chili.png
    - assets/food/coffee.png
    - assets/food/hotDog.png
    - assets/food/mashroom.png
    - assets/food/pineapple.png
    - assets/food/toast.png

    - assets/mood/mood1.png
    - assets/mood/mood2.png
    - assets/mood/mood3.png
    - assets/mood/mood4.png
    - assets/mood/mood5.png

    - assets/play/ball.png
    - assets/play/book.png
    - assets/play/box.png
    - assets/play/hide.png
    - assets/play/music.png
    - assets/play/safari.png

    - assets/explore/alpaca.png
    - assets/explore/balloon.png
    - assets/explore/champion.png
    - assets/explore/city.png
    - assets/explore/flower.png
    - assets/explore/horse.png
    - assets/explore/letter.png
    - assets/explore/mouse.png
    - assets/explore/parachute.png
    - assets/explore/pigeon.png
    - assets/explore/rose.png
    - assets/explore/ski.png
    - assets/explore/sleep.png
    - assets/explore/snake.png
    - assets/explore/soccer.png
    - assets/explore/surfing.png
    - assets/explore/tornado.png
    - assets/explore/trash.png
    - assets/explore/tree.png
    - assets/explore/ufo.png

    - assets/result/bat.png
    - assets/result/fire.png
    - assets/result/friendship.png
    - assets/result/gift.png
    - assets/result/koala.png
    - assets/result/mermaid.png
    - assets/result/panda.png
    - assets/result/pig.png
    - assets/result/shark.png
    - assets/result/snail.png
    - assets/result/tiger.png
    - assets/result/unicorn.png
    - assets/result/world.png










